version: '2.2'

networks:
  ros:
    driver: bridge

services:
  ros-master:
    image: ros-web:latest
    container_name: ros-master
    command: stdbuf -o L roscore
    networks:
      - ros
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=ros-master"
    restart: always

  ros-web-dev-container:
    image: ros-web:latest
    container_name: ros-web-dev-container
    networks:
      - ros
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=ros-web-dev-container"
      - "DISPLAY=unix$DISPLAY" 
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw 
      - ~/github/ros-web:/root/catkin_ws/src/ros-web
    command: tail -F anything
    privileged: true
    restart: always